name: Build

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - uses: extractions/setup-just@v1
      - uses: actions/setup-go@v4
      - name: test
        run: just test

      # - uses: meeDamian/github-release@2.0
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     name: Edge Builds
      #     tag: edge
      #     body: >
      #       This release is a build of the latest dev branch.
      #       It will update often so check back for new versions.
      #     files: >
      #       sbin/gwa_EDGE_linux_x64.zip
      #       sbin/gwa_EDGE_macos_x64.zip
      #       sbin/gwa_EDGE_win_x64.zip
      #     gzip: 'false'
      #     allow_override: 'true'
      #     prerelease: 'true'
