name: Release from master

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      tag_name:
        required: true
        type: string

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          GWA_API_HOST: ${{ secrets.GWA_API_HOST }}
          GWA_CLIENT_ID: ${{ secrets.GWA_CLIENT_ID }}
          GWA_VERSION: ${{ inputs.tag_name }}
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      - name: test
        run: just test
      - name: generate commands documentation
        run: just docs
      - name: Commit docs
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Generate new docs'
          add: 'docs/*.md'
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GWA_API_HOST: ${{ secrets.GWA_API_HOST }}
          GWA_CLIENT_ID: ${{ secrets.GWA_CLIENT_ID }}
          GWA_VERSION: ${{ inputs.tag_name }}

