name: Pre-release

on:
  push:
    branches:
      - pre-release

env:
  GWA_API_HOST: api.gov.bc.ca
  GWA_CLIENT_ID: gwa-cli
  GWA_VERSION: v3

jobs:
  release-tag:
    name: create release tag
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - id: release
        uses: rymndhng/release-on-push-action@v0.28.0
        with:
          bump_version_scheme: major
          release_body: "This is a prerelease version intended for testing purposes. It may contain new features, improvements, and bug fixes that are not yet fully stable. We encourage you to try it out and provide feedback. If you encounter any issues, please report them on our issue tracker. Thank you for helping us improve!"
    outputs:
      version_number: ${{ steps.release.outputs.tag_name }}

  goreleaser:
    runs-on: ubuntu-latest
    needs: release-tag
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: extractions/setup-just@v1
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      - name: Run Unit Tests
        run: just test
      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: v1.20.0
          args: release --verbose --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CLI_VERSION: ${{ needs.release-tag.outputs.version_number }}
